name: prusa-slicer
base: core20
adopt-info: prusa-slicer
summary: Powerful 3D printing slicer optimized for Prusa printers
description: |
    PrusaSlicer takes 3D models (STL, OBJ, AMF) and converts them into G-code instructions for FFF printers or PNG layers for mSLA 3D printers. It's compatible with any modern printer based on the RepRap toolchain, including all those based on the Marlin, Prusa, Sprinter and Repetier firmware. It also works with Mach3, LinuxCNC and Machinekit controllers.
    PrusaSlicer is based on Slic3r by Alessandro Ranelucci and the RepRap community

architectures:
    - build-on: amd64
      run-on: amd64

compression: lzo
grade: stable
confinement: strict

plugs:
    gtk-3-themes:
        default-provider: gtk-common-themes
        interface: content
        target: $SNAP/data-dir/themes
    icon-themes:
        default-provider: gtk-common-themes
        interface: content
        target: $SNAP/data-dir/icons
    sound-themes:
        default-provider: gtk-common-themes
        interface: content
        target: $SNAP/data-dir/sounds

layout:
    /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
        bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
    /usr/share/xml/iso-codes:
        bind: $SNAP/usr/share/xml/iso-codes
    /usr/local/share/PrusaSlicer:
        symlink: $SNAP/usr/local/share/PrusaSlicer
    /usr/share/libdrm:
        symlink: $SNAP/usr/share/libdrm

apps:
    prusa-slicer:
        common-id: com.prusa3d.PrusaSlicer
        environment:
            PATH: $SNAP/usr/local/bin:$PATH
            DISABLE_WAYLAND: 1
            GTK_USE_PORTAL: 1
            GTK_DATA_PREFIX: $SNAP
            XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
        command: usr/local/bin/prusa-slicer
        command-chain: [ bin/desktop-launch ]
        desktop: usr/local/share/applications/PrusaSlicer.desktop
        plugs:
            - desktop
            - desktop-legacy
            - gsettings
            - wayland
            - x11
            - unity7
            - opengl
            - home
            - network
            - removable-media
            - mount-observe
            - hardware-observe
            - raw-usb
            - udisks2

    prusa-gcodeviewer:
        environment:
            PATH: $SNAP/usr/local/bin:$PATH
            DISABLE_WAYLAND: 1
            GTK_USE_PORTAL: 1
            GTK_DATA_PREFIX: $SNAP
            XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
        command: usr/local/bin/prusa-slicer --gcodeviewer
        command-chain: [ bin/desktop-launch ]
        desktop: usr/local/share/applications/PrusaGcodeviewer.desktop
        plugs:
            - desktop
            - desktop-legacy
            - gsettings
            - wayland
            - x11
            - unity7
            - opengl
            - home
            - network
            - removable-media
            - mount-observe

parts:
    desktop-gtk3:
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: gtk
        plugin: make
        make-parameters: ["FLAVOR=gtk3"]

        filesets:
            no-doc:
                - -usr/share/man
                - -usr/share/doc
                - -usr/share/doc-base
            no-theming:
                - -usr/share/themes
                - -usr/share/icons
                - -usr/share/sounds

        build-packages:
            - build-essential
            - libgtk-3-dev

        stage-packages:
            - libxkbcommon0  # XKB_CONFIG_ROOT
            - ttf-ubuntu-font-family
            - dmz-cursor-theme
            - light-themes
            - adwaita-icon-theme
            - gnome-themes-standard
            - shared-mime-info
            - libgtk-3-0
            - libgdk-pixbuf2.0-0
            - libglib2.0-bin
            - libgtk-3-bin
            - unity-gtk3-module
            - libappindicator3-1
            - locales-all
            - xdg-user-dirs
            - ibus-gtk3
            - libibus-1.0-5
            - fcitx-frontend-gtk3
            - libgtk2.0-0
            - libcanberra-gtk3-module

        override-prime: |
            snapcraftctl prime
            glib-compile-schemas "${SNAPCRAFT_PRIME}/usr/share/glib-2.0/schemas"

        prime:
            - $no-doc
            - $no-theming

    patches:
        source: ./patches
        plugin: dump
        organize:
            '*.patch': patches/
        prime:
            - -patches/

    prusa-slicer:
        after:
            - desktop-gtk3
            - patches
        plugin: cmake
        source: https://github.com/prusa3d/PrusaSlicer.git
        source-tag: version_2.4.2

        filesets:
            no-doc:
                - -usr/share/man
                - -usr/share/doc
                - -usr/share/doc-base

        build-packages:
            - build-essential
            - ccache
            - cmake
            - gettext
            - git
            - libgl1-mesa-dev
            - libglew-dev
            - libudev-dev
            - libdbus-1-dev
            - m4

        stage-packages:
            - libglu1-mesa
            - libdrm-common
            - libopengl0
            - util-linux
            - udisks2

        override-pull: |
            snapcraftctl pull
            _pkgversion="snap2"
            _version="$(git describe --tags | cut -d_ -f2 | grep -o '^[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+\(-[A-z0-9]\+\)\?')"

            # Set Snap package version
            snapcraftctl set-version "${_version}+${_pkgversion}"
            sed -i "s/set(SLIC3R_BUILD_ID \"PrusaSlicer-\${SLIC3R_VERSION}+UNKNOWN\")/set(SLIC3R_BUILD_ID \"PrusaSlicer-\${SLIC3R_VERSION}+${_pkgversion}\")/g" version.inc

            if [ -d "${SNAPCRAFT_STAGE}/patches" ]; then
                # Apply patches
                git apply "${SNAPCRAFT_STAGE}"/patches/*
            fi

        override-build: |
            cp -a "${SNAPCRAFT_PART_SRC}"/* "${SNAPCRAFT_PART_BUILD}"

            # Build dependencies, as configured upstream
            cd deps
            cmake -DCMAKE_PREFIX_PATH=usr/local -DDESTDIR=/ -DDEP_WX_GTK3=1
            make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
            cd ..

            # Build slicer
            cmake "${SNAPCRAFT_PART_BUILD}" \
                -DSLIC3R_ASAN=0 \
                -DSLIC3R_STATIC=1 \
                -DSLIC3R_FHS=1 \
                -DSLIC3R_BUILD_TESTS=OFF \
                -DSLIC3R_GTK=3 \
                -DSLIC3R_DESKTOP_INTEGRATION=0 \
                -DCMAKE_BUILD_TYPE=Release
            make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT && make "DESTDIR=${SNAPCRAFT_PART_INSTALL}" install

        override-prime: |
            snapcraftctl prime

            sed -i 's|^[[:blank:]]*Icon=.*$|Icon=/usr/local/share/icons/hicolor/192x192/apps/PrusaSlicer.png|' "${SNAPCRAFT_PRIME}/usr/local/share/applications/PrusaSlicer.desktop"
            sed -i 's|^[[:blank:]]*Icon=.*$|Icon=/usr/local/share/icons/hicolor/192x192/apps/PrusaSlicer-gcodeviewer.png|' "${SNAPCRAFT_PRIME}/usr/local/share/applications/PrusaGcodeviewer.desktop"

            # "Dangling" link, 'causing store to reject upload
            rm "${SNAPCRAFT_PRIME}/usr/local/share/PrusaSlicer/resources"

        prime:
            - $no-doc

