name: prusa-slicer
base: core20
adopt-info: prusa-slicer
architectures:
  - build-on: amd64
    run-on: amd64

summary: PrusaSlicer converts 3D models into code instructions for 3D printers.
description: |
  PrusaSlicer takes 3D models (STL, OBJ, AMF) and converts them into G-code instructions
  for FFF printers or PNG layers for mSLA 3D printers. It's compatible with any modern printer
  based on the RepRap toolchain, including all those based on the Marlin, Prusa, Sprinter and
  Repetier firmware. It also works with Mach3, LinuxCNC and Machinekit controllers.

  PrusaSlicer is based on Slic3r by Alessandro Ranelucci and the RepRap community

  Key features are:
    - multi-platform (Linux/Mac/Win) and packaged as standalone-app with no dependencies required
    - complete command-line interface to use it with no GUI
    - multi-material (multiple extruders) object printing
    - multiple G-code flavors supported (RepRap, Makerbot, Mach3, Machinekit etc.)
    - ability to plate multiple objects having distinct print settings
    - multithread processing
    - STL auto-repair (tolerance for broken models)
    - wide automated unit testing

  Other major features are:
    - combine infill every 'n' perimeters layer to speed up printing
    - 3D preview (including multi-material files)
    - multiple layer heights in a single print
    - spiral vase mode for bumpless vases
    - fine-grained configuration of speed, acceleration, extrusion width
    - several infill patterns including honeycomb, spirals, Hilbert curves
    - support material, raft, brim, skirt
    - standby temperature and automatic wiping for multi-extruder printing
    - customizable G-code macros and output filename with variable placeholders
    - support for post-processing scripts
    - cooling logic controlling fan speed and dynamic print speed

grade: stable
confinement: strict
icon: snap/gui/prusa-slicer.png

layout:
  /usr/local/share/PrusaSlicer:
    symlink: $SNAP/usr/local/share/PrusaSlicer
  /usr/share/libdrm:
    symlink: $SNAP/usr/share/libdrm

apps:
  prusa-slicer:
    environment:
      PATH: $SNAP/usr/local/bin:$PATH
      DISABLE_WAYLAND: 1
    command: bin/desktop-launch $SNAP/usr/local/bin/prusa-slicer
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - opengl
      - home
      - network
      - optical-drive
      - removable-media
      - mount-observe
      - hardware-observe
      - raw-usb

parts:
  desktop-gtk2:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk2"]
    build-packages:
      - build-essential
      - libgtk2.0-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - unity-gtk2-module
      - locales-all
      - libappindicator1
      - xdg-user-dirs
      - ibus-gtk
      - libibus-1.0-5

  upstream-deps:
    after:
      - desktop-gtk2
    plugin: cmake
    source: https://github.com/prusa3d/PrusaSlicer.git
    source-tag: version_2.3.0-alpha1
    build-packages:
      - build-essential
      - ccache
      - cmake
      - gettext
      - git
      - m4
      - libgl1-mesa-dev
      - libglew-dev
    override-build: |
      git config --global user.email "ivo.cavalcante@gmail.com"
      git config --global user.name "Ivo Cavalcante"
      cmake "${SNAPCRAFT_PART_SRC}/deps" -DCMAKE_PREFIX_PATH=usr/local -DDESTDIR=/
      make -j$(nproc)

  prusa-slicer:
    after:
      - desktop-gtk2
      - upstream-deps
    plugin: cmake
    source: https://github.com/prusa3d/PrusaSlicer.git
    source-tag: version_2.3.0-alpha1
    build-packages:
      - build-essential
      - ccache
      - cmake
      - git
      - libudev-dev
      - libdbus-1-dev
    stage-packages:
      - libglu1-mesa
      - libdrm-common
      - libopengl0
    override-build: |
      _version="$(git describe --tags | cut -d_ -f2)"
      snapcraftctl set-version "$_version"

      cmake "${SNAPCRAFT_PART_SRC}" \
        -DSLIC3R_ASAN=0 \
        -DSLIC3R_STATIC=1 \
        -DSLIC3R_FHS=1
      make -j$(nproc) && make "DESTDIR=${SNAPCRAFT_PART_INSTALL}" install

